# Generated by Django 4.2.1 on 2023-06-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qp', '0002_choice_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='question_images'),
        ),
    ]
