# Generated by Django 4.2.1 on 2023-07-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qp', '0005_imagecontent_remove_choice_img_remove_question_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecontent',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
