# Generated by Django 4.2.1 on 2023-06-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
        ("student_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_profile",
            name="bio",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="student_profile",
            name="courses",
            field=models.ManyToManyField(blank=True, to="course.course"),
        ),
    ]
