# Generated by Django 4.2.1 on 2023-06-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_profile", "0002_student_profile_bio_student_profile_courses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student_profile",
            name="bio",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
