# Generated by Django 4.2.1 on 2023-06-15 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_profile", "0002_password_reset"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_profile",
            name="username",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="password_reset",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 16, 15, 36, 29, 686278)
            ),
        ),
    ]
