# Generated by Django 4.2.1 on 2023-06-15 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "student_profile",
            "0003_student_profile_username_alter_password_reset_expiry",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="password_reset",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 16, 16, 37, 12, 867519)
            ),
        ),
        migrations.AlterField(
            model_name="student_profile",
            name="dp",
            field=models.URLField(blank=True, null=True),
        ),
    ]
