# Generated by Django 4.2.1 on 2023-06-15 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "student_profile",
            "0004_alter_password_reset_expiry_alter_student_profile_dp",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="password_reset",
            name="token",
        ),
        migrations.AddField(
            model_name="password_reset",
            name="otp",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="password_reset",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="password_reset",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 16, 5, 34, 46, 6262)
            ),
        ),
    ]
