# Generated by Django 4.2.1 on 2023-06-15 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "student_profile",
            "0005_remove_password_reset_token_password_reset_otp_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="password_reset",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 16, 0, 42, 39, 19903, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
