# Generated by Django 4.2.1 on 2023-06-21 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0006_alter_password_reset_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password_reset',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 13, 2, 24, 670647, tzinfo=datetime.timezone.utc)),
        ),
    ]
