# Generated by Django 4.2.1 on 2023-06-21 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0007_alter_password_reset_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password_reset',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 13, 32, 48, 451257, tzinfo=datetime.timezone.utc)),
        ),
    ]
