# Generated by Django 4.2.1 on 2023-06-21 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0008_alter_password_reset_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password_reset',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 23, 46, 5, 366431, tzinfo=datetime.timezone.utc)),
        ),
    ]
