# Generated by Django 4.2.1 on 2023-06-28 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0012_alter_password_reset_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password_reset',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 16, 41, 14, 401516, tzinfo=datetime.timezone.utc)),
        ),
    ]
