# Generated by Django 4.2.1 on 2023-06-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_paper", "0004_testquestion_marks_testquestion_submitted"),
    ]

    operations = [
        migrations.AddField(
            model_name="testpaper",
            name="submitted",
            field=models.BooleanField(default=False),
        ),
    ]
